package:
  name: pypeliner
  version: "0.5.1"

source:
  git_url: https://bitbucket.org/dranew/pypeliner.git
  git_rev: v0.5.1

requirements:
  build:
    - python
    - networkx >=1.11

  run:
    - python
    - networkx >=1.11
    - dill
    - python-json-logger

test:
  requires:
    - nose

about:
  home: http://bitbucket.org/dranew/pypeliner
  license: MIT
  summary: "Library for creating informatic workflows"

