package:
  name: pypeliner
  version: "0.4.8"

source:
  git_url: https://dranew@bitbucket.org/dranew/pypeliner.git
  git_rev: v0.4.8

requirements:
  build:
    - python
    - networkx >=1.11

  run:
    - python
    - networkx >=1.11

test:
  requires:
    - nose

about:
  home: http://bitbucket.org/dranew/pypeliner
  license: MIT
  summary: "Library for creating informatic workflows"

