package:
  name: pypeliner
  version: "0.5.5"

source:
  git_url: https://github.com/shahcompbio/pypeliner.git
  git_rev: v0.5.5

requirements:
  build:
    - python 2.7*
    - dill
    - networkx
    - pyyaml

  run:
    - python 2.7*
    - networkx >=1.11
    - dill
    - pyyaml
    - nose

test:
  imports:
    - pypeliner

about:
  home: https://github.com/shahcompbio/pypeliner.git
  license: MIT
  summary: "Library for creating informatic workflows"

