package:
  name: pypeliner
  version: "0.5.9"

source:
  git_url: https://github.com/shahcompbio/pypeliner.git
  git_rev: v0.5.9

requirements:
  build:
    - python
    - dill
    - networkx
    - future
    - pyyaml

  run:
    - python
    - networkx >=1.11
    - dill
    - pyyaml
    - nose
    - future

test:
  imports:
    - pypeliner

about:
  home: https://github.com/shahcompbio/pypeliner.git
  license: MIT
  summary: "Library for creating informatic workflows"

